[package]
name = "zkboo-keccak"
version = "1.0.0"
edition = "2024"
license = "LGPL-3.0-or-later"
description = "Keccak-256 (Ethereum) and SHAKE256 as ZKBoo circuits."
repository = "https://github.com/zkboo/zkboo-keccak"
documentation = "https://docs.rs/zkboo-keccak"
readme = "README.md"
keywords = ["zk", "zero-knowledge", "zkboo", "keccak", "shake256"]
categories = ["cryptography", "no-std"]

[dependencies]
zkboo = { version = "1.0.0", features = ["u64"] }

[dev-dependencies]
zkboo = { version = "1.0.0", features = ["u64", "keccak"] }
